services:
  mysql-db:
    image: mysql:8.0
    container_name: weather_db
    restart: always
    environment:

      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "${DB_PORT_EXTERNAL}:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  flask-api:
    build: .
    container_name: flask-api
    restart: always
    ports:
      - "5050:5050"
    depends_on:
      - mysql-db

    env_file:
      - .env
    environment:

      MYSQL_HOST: mysql-db
      MYSQL_USER: root
      MYSQL_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DB: ${DB_NAME}
    volumes:
      - ./backend:/app/backend
      - ./raw:/app/raw 
      - ./frontend:/app/frontend

volumes:
  mysql-data: